[project]
name = "gazebodistro"
version = "0.1.0"
description = "Add a short description here"
authors = ["Michael Carroll <mjcarroll@intrinsic.ai>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
cli11 = "2.3.2.*"
eigen = "3.4.0.*"
python = "3.11.5.*"
cppzmq = "4.10.0.*"

[host-dependencies]
libcurl = "8.2.1.*"
yaml = "0.2.5.*"
tinyxml2 = "9.0.0.*"
libzip = "1.10.1.*"
libprotobuf = "4.23.4.*"
jsoncpp = "1.9.5.*"
python = "3.11.5.*"
pytest = "7.4.1.*"
pybind11-abi = "4.*"
pip = "23.2.1.*"
pybind11 = "2.11.1.*"
ffmpeg = "6.0.0.*"
gts = "0.7.6.*"
assimp = "5.2.5.*"
freeimage = "3.18.0.*"
glib = "2.76.4.*"
libgdal = "3.7.1.*"
cppzmq = "4.10.0.*"
zeromq = "4.3.4.*"
sqlite = "3.43.0.*"
libode = "0.16.2.*"
bullet-cpp = "3.24.*"
dartsim = "6.13.0.*"
eigen = "3.4.0.*"

[build-dependencies]
compilers = "1.6.0.*"
ninja = "1.11.1.*"
cmake = "3.27.4.*"
pkgconfig = "1.5.5.*"
make = "4.3.*"
pybind11 = "2.11.1.*"
swig = "4.1.1.*"
pybind11-abi = "4.*"
pkg-config = "0.29.2.*"
pytest = "7.4.1.*"
colcon-common-extensions = "0.3.0.*"
vcstool = "0.3.0.*"
git = "2.42.0.*"

[target.linux-64.host-dependencies]
libuuid = "2.38.1.*"

[target.win-64.host-dependencies]
dlfcn-win32 = "1.3.0.*"
