{
  "build": {
    "merge-install": true,
    "event-handlers": [
      "console_package_list+",
      "console_cohesion+",
    ],
    "cmake-args": [
      "--no-warn-unused-cli",
      "-DCMAKE_BUILD_TYPE=Release",
      "-DBUILD_DOCS=OFF",
      "-DSKIP_optix=ON",
      "-DSKIP_SWIG=ON",
      "-DCMAKE_C_COMPILER_LAUNCHER=buildcache",
      "-DCMAKE_CXX_COMPILER_LAUNCHER=buildcache",
    ]
  },
  "test": {
    "merge-install": true,
    "event-handlers": [
      "console_direct+",
    ],
    "executor": "sequential",
  }
}
